version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 919643955814.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker-compose -f docker-compose.yml build
  build:
    commands:
      - echo Tagging and pushing the Docker images...
      - docker tag client-repo:latest 919643955814.dkr.ecr.us-east-1.amazonaws.com/client-repo:latest
      - docker push 919643955814.dkr.ecr.us-east-1.amazonaws.com/client-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - docker-compose.yml
  discard-paths: yes